/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosIdRouteImport } from './routes/proyectos.$id'
import { Route as ProyectosIdSugerenciasRouteImport } from './routes/proyectos.$id.sugerencias'
import { Route as ProyectosIdPiezasRouteImport } from './routes/proyectos.$id.piezas'
import { Route as ProyectosIdParrillaRouteImport } from './routes/proyectos.$id.parrilla'
import { Route as ProyectosIdEvaluacionRouteImport } from './routes/proyectos.$id.evaluacion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIdRoute = ProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIdSugerenciasRoute = ProyectosIdSugerenciasRouteImport.update({
  id: '/sugerencias',
  path: '/sugerencias',
  getParentRoute: () => ProyectosIdRoute,
} as any)
const ProyectosIdPiezasRoute = ProyectosIdPiezasRouteImport.update({
  id: '/piezas',
  path: '/piezas',
  getParentRoute: () => ProyectosIdRoute,
} as any)
const ProyectosIdParrillaRoute = ProyectosIdParrillaRouteImport.update({
  id: '/parrilla',
  path: '/parrilla',
  getParentRoute: () => ProyectosIdRoute,
} as any)
const ProyectosIdEvaluacionRoute = ProyectosIdEvaluacionRouteImport.update({
  id: '/evaluacion',
  path: '/evaluacion',
  getParentRoute: () => ProyectosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proyectos/$id': typeof ProyectosIdRouteWithChildren
  '/proyectos/': typeof ProyectosIndexRoute
  '/proyectos/$id/evaluacion': typeof ProyectosIdEvaluacionRoute
  '/proyectos/$id/parrilla': typeof ProyectosIdParrillaRoute
  '/proyectos/$id/piezas': typeof ProyectosIdPiezasRoute
  '/proyectos/$id/sugerencias': typeof ProyectosIdSugerenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proyectos/$id': typeof ProyectosIdRouteWithChildren
  '/proyectos': typeof ProyectosIndexRoute
  '/proyectos/$id/evaluacion': typeof ProyectosIdEvaluacionRoute
  '/proyectos/$id/parrilla': typeof ProyectosIdParrillaRoute
  '/proyectos/$id/piezas': typeof ProyectosIdPiezasRoute
  '/proyectos/$id/sugerencias': typeof ProyectosIdSugerenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proyectos/$id': typeof ProyectosIdRouteWithChildren
  '/proyectos/': typeof ProyectosIndexRoute
  '/proyectos/$id/evaluacion': typeof ProyectosIdEvaluacionRoute
  '/proyectos/$id/parrilla': typeof ProyectosIdParrillaRoute
  '/proyectos/$id/piezas': typeof ProyectosIdPiezasRoute
  '/proyectos/$id/sugerencias': typeof ProyectosIdSugerenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/proyectos/$id'
    | '/proyectos/'
    | '/proyectos/$id/evaluacion'
    | '/proyectos/$id/parrilla'
    | '/proyectos/$id/piezas'
    | '/proyectos/$id/sugerencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/proyectos/$id'
    | '/proyectos'
    | '/proyectos/$id/evaluacion'
    | '/proyectos/$id/parrilla'
    | '/proyectos/$id/piezas'
    | '/proyectos/$id/sugerencias'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/proyectos/$id'
    | '/proyectos/'
    | '/proyectos/$id/evaluacion'
    | '/proyectos/$id/parrilla'
    | '/proyectos/$id/piezas'
    | '/proyectos/$id/sugerencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProyectosIdRoute: typeof ProyectosIdRouteWithChildren
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$id': {
      id: '/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof ProyectosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$id/sugerencias': {
      id: '/proyectos/$id/sugerencias'
      path: '/sugerencias'
      fullPath: '/proyectos/$id/sugerencias'
      preLoaderRoute: typeof ProyectosIdSugerenciasRouteImport
      parentRoute: typeof ProyectosIdRoute
    }
    '/proyectos/$id/piezas': {
      id: '/proyectos/$id/piezas'
      path: '/piezas'
      fullPath: '/proyectos/$id/piezas'
      preLoaderRoute: typeof ProyectosIdPiezasRouteImport
      parentRoute: typeof ProyectosIdRoute
    }
    '/proyectos/$id/parrilla': {
      id: '/proyectos/$id/parrilla'
      path: '/parrilla'
      fullPath: '/proyectos/$id/parrilla'
      preLoaderRoute: typeof ProyectosIdParrillaRouteImport
      parentRoute: typeof ProyectosIdRoute
    }
    '/proyectos/$id/evaluacion': {
      id: '/proyectos/$id/evaluacion'
      path: '/evaluacion'
      fullPath: '/proyectos/$id/evaluacion'
      preLoaderRoute: typeof ProyectosIdEvaluacionRouteImport
      parentRoute: typeof ProyectosIdRoute
    }
  }
}

interface ProyectosIdRouteChildren {
  ProyectosIdEvaluacionRoute: typeof ProyectosIdEvaluacionRoute
  ProyectosIdParrillaRoute: typeof ProyectosIdParrillaRoute
  ProyectosIdPiezasRoute: typeof ProyectosIdPiezasRoute
  ProyectosIdSugerenciasRoute: typeof ProyectosIdSugerenciasRoute
}

const ProyectosIdRouteChildren: ProyectosIdRouteChildren = {
  ProyectosIdEvaluacionRoute: ProyectosIdEvaluacionRoute,
  ProyectosIdParrillaRoute: ProyectosIdParrillaRoute,
  ProyectosIdPiezasRoute: ProyectosIdPiezasRoute,
  ProyectosIdSugerenciasRoute: ProyectosIdSugerenciasRoute,
}

const ProyectosIdRouteWithChildren = ProyectosIdRoute._addFileChildren(
  ProyectosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProyectosIdRoute: ProyectosIdRouteWithChildren,
  ProyectosIndexRoute: ProyectosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
